name: Building and pushing Logger service image to Docker Hub
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
    paths:
      - 'listener/**'
    branches:
      - main
jobs:
  building:
    name: Building Auth service image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Definir TAG da imagem
        run: echo "IMAGE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226

      - name: Build Logger service image
        run: docker build -t perazzojoao/logger-service:latest -f ./Dockerfile .

      - name: Push Logger service image to Docker Hub
        run: |
          docker login -u perazzojoao -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push perazzojoao/logger-service:latest
          docker push perazzojoao/logger-service:${{ github.ref }}
